USE [master];
GO

SET QUOTED_IDENTIFIER ON;
SET ARITHABORT ON;
SET NUMERIC_ROUNDABORT OFF;
SET CONCAT_NULL_YIELDS_NULL ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
GO

RAISERROR
(
	N'Creando la base de datos "SERP"...',
	0,
	1
)
WITH NOWAIT;
GO

CREATE DATABASE [SERP]
CONTAINMENT = NONE
ON PRIMARY
(
    NAME = N'SERP',
    FILENAME = N'D:\Users\James\Documents\Microsoft SQL Server\MSSQL16.MSSQLSERVER2022\MSSQL\DATA\SERP.mdf',
    SIZE = 8192KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
)
LOG ON
(
    NAME = N'SERP_log',
    FILENAME = N'D:\Users\James\Documents\Microsoft SQL Server\MSSQL16.MSSQLSERVER2022\MSSQL\Log\SERP.ldf',
    SIZE = 8192KB,
    MAXSIZE = 2048GB,
    FILEGROWTH = 65536KB
)
WITH
	CATALOG_COLLATION = DATABASE_DEFAULT,
    LEDGER = OFF;
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXECUTE [SERP].[dbo].[sp_fulltext_database]
    @action = 'enable';
END;
GO

ALTER DATABASE [SERP]
SET ANSI_NULL_DEFAULT OFF;
GO

ALTER DATABASE [SERP]
SET ANSI_NULLS OFF;
GO

ALTER DATABASE [SERP]
SET ANSI_PADDING OFF;
GO

ALTER DATABASE [SERP]
SET ANSI_WARNINGS OFF;
GO

ALTER DATABASE [SERP]
SET ARITHABORT OFF;
GO

ALTER DATABASE [SERP]
SET AUTO_CLOSE OFF;
GO

ALTER DATABASE [SERP]
SET AUTO_SHRINK OFF;
GO

ALTER DATABASE [SERP]
SET AUTO_UPDATE_STATISTICS ON;
GO

ALTER DATABASE [SERP]
SET CURSOR_CLOSE_ON_COMMIT OFF;
GO

ALTER DATABASE [SERP]
SET CURSOR_DEFAULT GLOBAL;
GO

ALTER DATABASE [SERP]
SET CONCAT_NULL_YIELDS_NULL OFF;
GO

ALTER DATABASE [SERP]
SET NUMERIC_ROUNDABORT OFF;
GO

ALTER DATABASE [SERP]
SET QUOTED_IDENTIFIER OFF;
GO

ALTER DATABASE [SERP]
SET RECURSIVE_TRIGGERS OFF;
GO

ALTER DATABASE [SERP]
SET DISABLE_BROKER;
GO

ALTER DATABASE [SERP]
SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
GO

ALTER DATABASE [SERP]
SET DATE_CORRELATION_OPTIMIZATION OFF;
GO

ALTER DATABASE [SERP]
SET TRUSTWORTHY OFF;
GO

ALTER DATABASE [SERP]
SET ALLOW_SNAPSHOT_ISOLATION OFF;
GO

ALTER DATABASE [SERP]
SET PARAMETERIZATION SIMPLE;
GO

ALTER DATABASE [SERP]
SET READ_COMMITTED_SNAPSHOT OFF;
GO

ALTER DATABASE [SERP]
SET HONOR_BROKER_PRIORITY OFF;
GO

ALTER DATABASE [SERP]
SET RECOVERY FULL;
GO

ALTER DATABASE [SERP]
SET MULTI_USER;
GO

ALTER DATABASE [SERP]
SET PAGE_VERIFY CHECKSUM;
GO

ALTER DATABASE [SERP]
SET DB_CHAINING OFF;
GO

ALTER DATABASE [SERP]
SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF);
GO

ALTER DATABASE [SERP]
SET TARGET_RECOVERY_TIME = 60 SECONDS;
GO

ALTER DATABASE [SERP]
SET DELAYED_DURABILITY = DISABLED;
GO

ALTER DATABASE [SERP]
SET ACCELERATED_DATABASE_RECOVERY = OFF;
GO

ALTER DATABASE [SERP]
SET QUERY_STORE = ON;
GO

ALTER DATABASE [SERP]
SET QUERY_STORE
(
	OPERATION_MODE = READ_WRITE,
	CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
	DATA_FLUSH_INTERVAL_SECONDS = 900,
	INTERVAL_LENGTH_MINUTES = 60,
	MAX_STORAGE_SIZE_MB = 1000,
	QUERY_CAPTURE_MODE = AUTO,
	SIZE_BASED_CLEANUP_MODE = AUTO,
	MAX_PLANS_PER_QUERY = 200,
	WAIT_STATS_CAPTURE_MODE = ON
);
GO

ALTER DATABASE [SERP]
SET READ_WRITE;
GO

EXECUTE [SERP].[sys].[sp_addextendedproperty]
	@name = N'MS_Description',
	@value = N'Base de datos para gestión de SERP';
GO