:setvar path "Unidad:\Ruta\Al\Repositorio\Local\StoneERP\"
:r $(path)\Versions\00.00.00\Database.sql
:r $(path)\sys\Views\messages\51001.sql
:r $(path)\sys\Views\messages\51002.sql
:r $(path)\sys\Views\messages\51003.sql
:r $(path)\Security\Schemas\History.sql
:r $(path)\scripts_para_crear_tablas\company.sql
:r $(path)\scripts_para_crear_tablas\branch_office.sql
:r $(path)\scripts_para_crear_tablas\cost_center.sql
:r $(path)\scripts_para_crear_tablas\entity_catalog.sql
:r $(path)\scripts_para_crear_tablas\permission.sql
:r $(path)\scripts_para_crear_tablas\role.sql
:r $(path)\scripts_para_crear_tablas\user.sql
:r $(path)\scripts_para_crear_tablas\UserRole.sql
:r $(path)\scripts_para_crear_tablas\user_company.sql
:r $(path)\scripts_para_crear_tablas\permi_role.sql
:r $(path)\scripts_para_crear_tablas\permi_user.sql
:r $(path)\scripts_para_crear_tablas\permi_role_record.sql
:r $(path)\scripts_para_crear_tablas\permi_user_record.sql
:r $(path)\dbo\Functions\Table\RowLevelSecurity.sql
:r $(path)\dbo\Functions\Scalar\CUDSecurity.sql
:r $(path)\Security\Policies\dbo\RowLevelSecurityBranchOffice.sql
:r $(path)\Security\Policies\dbo\RowLevelSecurityCostCenter.sql
:r $(path)\dbo\Triggers\IDBranchOffice.sql
:r $(path)\dbo\Triggers\IIBranchOffice.sql
:r $(path)\dbo\Triggers\IUBranchOffice.sql
:r $(path)\dbo\Triggers\IDCostCenter.sql
:r $(path)\dbo\Triggers\IICostCenter.sql
:r $(path)\dbo\Triggers\IUCostCenter.sql
:r $(path)\dbo\Procedures\GetUserPermissions.sql
:r $(path)\dbo\Data\Company.sql
:r $(path)\dbo\Data\BranchOffice.sql
:r $(path)\dbo\Data\CostCenter.sql
:r $(path)\dbo\Data\EntityCatalog.sql
:r $(path)\dbo\Data\Permission.sql
:r $(path)\dbo\Data\Role.sql
:r $(path)\dbo\Data\User.sql
:r $(path)\dbo\Data\UserRole.sql
:r $(path)\dbo\Data\UserCompany.sql
:r $(path)\dbo\Data\PermiRole.sql
:r $(path)\dbo\Data\PermiUser.sql
:r $(path)\dbo\Data\PermiRoleRecord.sql
:r $(path)\dbo\Data\PermiUserRecord.sql
:r $(path)\Security\Logins\TestUser.sql
:r $(path)\Security\Users\TestUser.sql
--:r $(path)\TSQLt\tSQLt.class.sql
--:r $(path)\Tests\dbo\Functions\Table\RowLevelSecurity\testRowLevelSecurity.sql
--:r $(path)\Tests\dbo\Functions\Table\RowLevelSecurity\testRowLevelSecurityUserIsAdmin.sql
--EXECUTE [tSQLt].[RunAll]